name: Release Management

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run style:check

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run ts:check

  release:
    needs: validate
    if: "!contains(github.event.head_commit.message, 'chore(release): bump version')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install changelog tools
        run: |
          npm install -g conventional-changelog-cli
          npm install -g conventional-recommended-bump
          npm install -g conventional-changelog-angular

      - name: Get version bump type
        id: bump
        run: echo "bump=$(conventional-recommended-bump -p angular)" >> $GITHUB_OUTPUT

      - name: Bump version
        run: |
          npm version ${{ steps.bump.outputs.bump }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          npm install --package-lock-only

          if [ -f "android/build.gradle" ]; then
            sed -i "s/version = '.*'/version = '$NEW_VERSION'/" android/build.gradle
            sed -i "s/versionName \".*\"/versionName \"$NEW_VERSION\"/" android/build.gradle
            VERSION_CODE=$((10000 * $(echo $NEW_VERSION | cut -d. -f1) + 100 * $(echo $NEW_VERSION | cut -d. -f2) + $(echo $NEW_VERSION | cut -d. -f3)))
            sed -i "s/versionCode .*/versionCode $VERSION_CODE/" android/build.gradle
          fi

      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add package.json package-lock.json CHANGELOG.md android/build.gradle
          git commit -m "chore(release): bump version ${{ env.NEW_VERSION }}"
          git push

      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.NEW_VERSION }}
        run: gh release create $VERSION --draft --generate-notes
